#Last updated: 04/09/2026 19:28:26
[Forecast]
notavailable=No disponible
exceptional=Temps excepcional
forecast1=Temps estable i assolellat
forecast2=Bon temps
forecast3=Millorant a bon temps
forecast4=Bon temps, tornant-se menys estable
forecast5=Bon temps, possibles ruixats
forecast6=Prou bo, millorant
forecast7=Prou bo, possibles ruixats al principi
forecast8=Prou bo, ruixats més tard
forecast9=Ruixats al principi, millorant
forecast10=Variable, millorant
forecast11=Prou bo, probables ruixats
forecast12=Una mica variable, aclarint-se més tard
forecast13=Variable, probablement millorant
forecast14=Ruixats amb clarianes
forecast15=Ruixats, tornant-se més inestable
forecast16=Variable, una mica de pluja
forecast17=Variable, intervals curts de bon temps
forecast18=Variable, pluja més tard
forecast19=Variable, una mica de pluja
forecast20=Majoritàriament molt inestable
forecast21=Pluja ocasional, empitjorant
forecast22=Pluja a estones, molt inestable
forecast23=Pluja a intervals freqüents
forecast24=Pluja, molt inestable
forecast25=Tempestuós, podria millorar
forecast26=Tempestuós, molta pluja

[MoonPhases]
Newmoon=Lluna nova
WaxingCrescent=Creixent
FirstQuarter=Quart creixent
WaxingGibbous=Gibosa creixent
Fullmoon=Lluna plena
WaningGibbous=Gibosa minvant
LastQuarter=Quart minvant
WaningCrescent=Minvant

[Beaufort]
Calm=Calma
Lightair=Ventolina
Lightbreeze=Brisa molt feble
Gentlebreeze=Brisa feble
Moderatebreeze=Brisa moderada
Freshbreeze=Brisa fresca
Strongbreeze=Vent fort
Neargale=Vent molt fort
Gale=Temporal
Stronggale=Temporal fort
Storm=Temporal dur
Violentstorm=Temporal molt dur
Hurricane=Huracà
Unknown=DESCONEGUT

[Trends]
Risingveryrapidly=Pujant molt ràpidament
Risingquickly=Pujant ràpidament
Rising=Pujant
Risingslowly=Pujant lentament
Steady=Estable
Fallingslowly=Baixant lentament
Falling=Baixant
Fallingquickly=Baixant ràpidament
Fallingveryrapidly=Baixant molt ràpidament

[Compass]
N=N
NNE=NNE
NE=NE
ENE=ENE
E=E
ESE=ESE
SE=SE
SSE=SSE
S=S
SSW=SSO
SW=SO
WSW=OSO
W=O
WNW=ONO
NW=NO
NNW=NNO

[AirQualityCaptions]
Sensor1=pm2.5 Sensor 1
SensorAvg1=pm2.5 Mitjana Sensor 1
Sensor10-1=pm10 Sensor 1
Sensor10Avg1=pm10 Mitjana Sensor 1
Sensor2=pm2.5 Sensor 2
SensorAvg2=pm2.5 Mitjana Sensor 2
Sensor10-2=pm10 Sensor 2
Sensor10Avg2=pm10 Mitjana Sensor 2
Sensor3=pm2.5 Sensor 3
SensorAvg3=pm2.5 Mitjana Sensor 3
Sensor10-3=pm10 Sensor 3
Sensor10Avg3=pm10 Mitjana Sensor 3
Sensor4=pm2.5 Sensor 4
SensorAvg4=pm2.5 Mitjana Sensor 4
Sensor10-4=pm10 Sensor 4
Sensor10Avg4=pm10 Mitjana Sensor 4

[LeafWetnessCaptions]
Sensor1=Sensor 1
Sensor2=Sensor 2
Sensor3=Sensor 3
Sensor4=Sensor 4
Sensor5=Sensor 5
Sensor6=Sensor 6
Sensor7=Sensor 7
Sensor8=Sensor 8

[UserTempCaptions]
Sensor1=Sensor 1
Sensor2=Sensor 2
Sensor3=Sensor 3
Sensor4=Sensor 4
Sensor5=Sensor 5
Sensor6=Sensor 6
Sensor7=Sensor 7
Sensor8=Sensor 8

[ExtraTempCaptions]
Sensor1=Sensor 2 (T/H Exterior)
Sensor2=Dipòsit Buffer SH30 (Calefacció)
Sensor3=Sensor 3
Sensor4=Sensor 4
Sensor5=Sensor 5
Sensor6=Sensor 6
Sensor7=Sensor 7
Sensor8=Sensor 8
Sensor9=Sensor 9
Sensor10=Sensor 10
Sensor11=Sensor 11
Sensor12=Sensor 12
Sensor13=Sensor 13
Sensor14=Sensor 14
Sensor15=Sensor 15
Sensor16=Sensor 16

[ExtraHumCaptions]
Sensor1=Sensor 2 (Humitat Exterior)
Sensor2=Sensor 2
Sensor3=Sensor 3
Sensor4=Sensor 4
Sensor5=Sensor 5
Sensor6=Sensor 6
Sensor7=Sensor 7
Sensor8=Sensor 8
Sensor9=Sensor 9
Sensor10=Sensor 10
Sensor11=Sensor 11
Sensor12=Sensor 12
Sensor13=Sensor 13
Sensor14=Sensor 14
Sensor15=Sensor 15
Sensor16=Sensor 16

[ExtraDPCaptions]
Sensor1=Sensor 1
Sensor2=Sensor 2
Sensor3=Sensor 3
Sensor4=Sensor 4
Sensor5=Sensor 5
Sensor6=Sensor 6
Sensor7=Sensor 7
Sensor8=Sensor 8
Sensor9=Sensor 9
Sensor10=Sensor 10
Sensor11=Sensor 11
Sensor12=Sensor 12
Sensor13=Sensor 13
Sensor14=Sensor 14
Sensor15=Sensor 15
Sensor16=Sensor 16

[SoilTempCaptions]
Sensor1=Sensor 1
Sensor2=Sensor 2
Sensor3=Sensor 3
Sensor4=Sensor 4
Sensor5=Sensor 5
Sensor6=Sensor 6
Sensor7=Sensor 7
Sensor8=Sensor 8
Sensor9=Sensor 9
Sensor10=Sensor 10
Sensor11=Sensor 11
Sensor12=Sensor 12
Sensor13=Sensor 13
Sensor14=Sensor 14
Sensor15=Sensor 15
Sensor16=Sensor 16

[SoilMoistureCaptions]
Sensor1=Sensor 1
Sensor2=Sensor 2
Sensor3=Sensor 3
Sensor4=Sensor 4
Sensor5=Sensor 5
Sensor6=Sensor 6
Sensor7=Sensor 7
Sensor8=Sensor 8
Sensor9=Sensor 9
Sensor10=Sensor 10
Sensor11=Sensor 11
Sensor12=Sensor 12
Sensor13=Sensor 13
Sensor14=Sensor 14
Sensor15=Sensor 15
Sensor16=Sensor 16

[LaserCaptions]
Sensor1=Sensor 1
Sensor2=Sensor 2
Sensor3=Sensor 3
Sensor4=Sensor 4

[CO2Captions]
CO2-Current=CO&#8322 Actual
CO2-24hr=CO&#8322 Mitjana 24h
CO2-Pm2p5=PM 2.5
CO2-Pm2p5-24hr=PM 2.5 Mitjana 24h
CO2-Pm10=PM 10
CO2-Pm10-24hr=PM 10 Mitjana 24h
CO2-Temperature=Temperatura
CO2-Humidity=Humitat

[Snow]
SnowDepth=Gruix de neu
Snow24h=Nevada 24h

[Solar]
LessDaylightTomorrow=Demà hi haurà {0}min {1}s menys de llum solar
MoreDaylightTomorrow=Demà hi haurà {0}min {1}s més de llum solar

[DavisForecast1]
forecast1=EL PRONÒSTIC REQUEREIX 3 HORES DE DADES RECENTS
forecast2=Majoritàriament ennuvolat amb pocs canvis de temperatura.
forecast3=Majoritàriament ennuvolat i més fresc.
forecast4=Aclarint-se, més fresc i ventós.
forecast5=Aclarint-se i més fresc.
forecast6=Augment dels núvols i més fresc.
forecast7=Augment dels núvols amb pocs canvis de temperatura.
forecast8=Augment dels núvols i més càlid.
forecast9=Majoritàriament clar durant 12 a 24 hores amb pocs canvis de temperatura.
forecast10=Majoritàriament clar durant 6 a 12 hores amb pocs canvis de temperatura.
forecast11=Majoritàriament clar i més càlid.
forecast12=Majoritàriament clar durant 12 a 24 hores i més fresc.
forecast13=Majoritàriament clar durant 12 hores amb pocs canvis de temperatura.
forecast14=Majoritàriament clar amb pocs canvis de temperatura.
forecast15=Majoritàriament clar i més fresc.
forecast16=Parcialment ennuvolat, pluja i/o neu possible o continuada.
forecast17=Parcialment ennuvolat, neu possible o continuada.
forecast18=Parcialment ennuvolat, pluja possible o continuada.
forecast19=Majoritàriament ennuvolat, pluja i/o neu possible o continuada.
forecast20=Majoritàriament ennuvolat, neu possible o continuada.
forecast21=Majoritàriament ennuvolat, pluja possible o continuada.
forecast22=Majoritàriament ennuvolat.
forecast23=Parcialment ennuvolat.
forecast24=Majoritàriament clar.
forecast25=Parcialment ennuvolat amb pocs canvis de temperatura.
forecast26=Parcialment ennuvolat i més fresc.
forecast27=Regla de pronòstic desconeguda.

[DavisForecast2]
forecast1=
forecast2=Precipitació possible en 48 hores.
forecast3=Precipitació possible en 24 a 48 hores.
forecast4=Precipitació possible en 24 hores.
forecast5=Precipitació possible en 12 a 24 hores.
forecast6=Precipitació possible en 12 hores, localment forta a estones.
forecast7=Precipitació possible en 12 hores.
forecast8=Precipitació possible en 6 a 12 hores.
forecast9=Precipitació possible en 6 a 12 hores, localment forta a estones.
forecast10=Precipitació possible i ventós en 6 hores.
forecast11=Precipitació possible en 6 hores.
forecast12=La precipitació cessarà en 12 a 24 hores.
forecast13=Precipitació localment forta a estones, cessant en 12 hores.
forecast14=La precipitació cessarà en 12 hores.
forecast15=La precipitació cessarà en 6 hores.
forecast16=Precipitació probable, localment forta a estones.
forecast17=Precipitació probable.
forecast18=Precipitació continuada, localment forta a estones.
forecast19=Precipitació continuada.

[DavisForecast3]
forecast1=
forecast2=Ventós amb possible gir del vent a O, SO o S.
forecast3=Possible gir del vent a O, SO o S.
forecast4=Ventós amb possible gir del vent a O, NO o N.
forecast5=Possible gir del vent a O, NO o N.
forecast6=Ventós.
forecast7=Vent en augment.

[AlarmEmails]
subject=Alarma de Cumulus MX
preamble=S'ha activat una alarma de Cumulus MX.
windGustAbove=S'ha registrat una ràfega de vent superior a {0} {1}.
pressureAbove=La pressió ha pujat per sobre de {0} {1}.
tempAbove=La temperatura ha pujat per sobre de {0} {1}.
pressBelow=La pressió ha baixat per sota de {0} {1}.
tempBelow=La temperatura ha baixat per sota de {0} {1}.
pressDown=La pressió ha disminuït més de {0} {1}.
pressUp=La pressió ha augmentat més de {0} {1}.
rainAbove=La pluja d'avui ha superat els {0} {1}.
rainRateAbove=La intensitat de la pluja ha superat els {0} {1}.
sensorLost=S'ha perdut el contacte amb un sensor remot.
tempDown=La temperatura ha disminuït més de {0} {1}.
tempUp=La temperatura ha augmentat més de {0} {1}.
windAbove=La velocitat mitjana del vent ha superat els {0} {1}.
dataStopped=Cumulus ha deixat de rebre dades de la vostra estació meteorològica.
batteryLow=S'ha detectat un estat de bateria baixa.
dataSpike=S'ha suprimit un pic anòmal de dades de l'estació.
upgrade=Hi ha una actualització de Cumulus MX disponible.
firmware=Hi ha una actualització de microprogramari de l'estació disponible.
httpStopped=Les pujades HTTP de tercers estan fallant.
mySqlStopped=Les pujades a MySQL estan fallant.
isRaining=Ha començat a ploure.
newRecord=S'ha establert un nou rècord absolut.
ftpStopped=Les pujades per FTP s'han aturat.
genError=S'ha produït un error a Cumulus MX.

[AlarmNames]
windGustAbove=Ràfega alta
pressureAbove=Pressió alta
tempAbove=Temperatura alta
pressBelow=Pressió baixa
tempBelow=Temperatura baixa
pressDown=Pressió baixant
pressUp=Pressió pujant
rainAbove=Pluja d'avui
rainRateAbove=Intensitat de pluja alta
sensorLost=Pèrdua de dades del sensor
tempDown=Temp baixant
tempUp=Temp pujant
windAbove=Vent fort
dataStopped=Dades aturades
batteryLow=Bateria baixa
dataSpike=Pic de dades
upgrade=Actualització CMX
firmware=Actualització microprogramari
httpStopped=Pujada HTTP
mySqlStopped=Pujada MySQL
isRaining=Està plovent
newRecord=Nou rècord
ftpStopped=Pujada Web
genError=Error Cumulus MX

[WebTags]
GeneralTimeDate=HH:mm 'del' dd MMMM yyyy
GeneralDate=dd MMMM yyyy
GeneralTime=HH:mm
RecordDate='el' dd MMMM yyyy
RecordTimeDate='a les' HH:mm 'del' dd MMMM yyyy
RecordDryWetDate='fins al' dd MMMM yyyy
ElapsedTime={0:%d} dies {0:%h} hores
