server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Regles de control d'accés per seguretat (Només Tailscale, Docker i Localhost)
    allow 100.64.0.0/10;
    allow fd7a:115c:a1e0::/48;
    allow 172.16.0.0/12;
    allow 127.0.0.1;
    allow ::1;
    deny all;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
    }

    location /healthz {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
